version:  "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql://postgres:ishallbeaccepted@postgres/fastapi
      - SECRET_KEY=5cd00af19605d868c140f42d4d464c11d24c54f6889eb68b2fe2d2de57db8a08
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - ALGORITHM=HS256
  postgres:
    image: postgres
    environment:
        - POSTGRES_PASSWORD=ishallbeaccepted
        - POSTGRES_DB=fastapi

    volumes:
        - postgres-db:/var/lib/postgresql/data

volumes:
    postgres-db: